### ISSUE TITLE
0.3 version does not install from pypi

### ISSUE THREAD

**Issue by scottbessler** [garethr/cloth#3]
```
$ sudo easy_install cloth
Searching for cloth
Reading http://pypi.python.org/simple/cloth/
Reading https://github.com/garethr/cloth/
Best match: cloth 0.3.linux-x86-64
Downloading http://pypi.python.org/packages/any/c/cloth/cloth-0.3.linux-x86_64.tar.gz#md5=272567c33ecb0e52c1efaed1617370e3
Processing cloth-0.3.linux-x86_64.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-AKV1Pq/cloth-0.3.linux-x86_64.tar.gz
```

or via pip

```
$ sudo pip install cloth
Downloading/unpacking cloth
  Downloading cloth-0.3.linux-x86_64.tar.gz
  Running setup.py egg_info for package cloth
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '[redacted]build/cloth/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '[redacted]build/cloth/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in [redacted]build/cloth
```

**Comment by garethr** [comment]
I think I've just fixed this by removing one of the artefacts from pypi, specifically I'd run bdist, as well as sdist and bdist_egg which it looks like you're pip run picked up.

Let me know if that works, I've just tried that out locally in a fresh virtualenv.

**Comment by scottbessler** [comment]
yup, works great, thanks for the speedy fixes and merges!
